import { precacheAndRoute } from 'workbox-precaching';

// Precaching generated by vite-plugin-pwa
precacheAndRoute(self.__WB_MANIFEST || []);

self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const data = event.data.json();
    const title = data.title || 'AK Flow Notification';
    const options = {
      body: data.body,
      icon: data.icon || '/logo.png',
      badge: '/logo.png',
      sound: '/notification.mp3',
      data: {
        url: data.url || '/'
      },
      vibrate: [200, 100, 200, 100, 200],
      tag: data.tag || 'notification-' + Date.now()
    };

    event.waitUntil(
      self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
        const isVisible = clients.some((client) => client.visibilityState === 'visible');
        if (isVisible) {
          // If the application tab is open and currently visible to the user,
          // suppress OS-level push notification banner so the user isn't doubly interrupted while inside the app.
          return;
        } else {
          // If the app is minimized, closed, or running in a background tab,
          // show the OS push notification banner and play alert sound to wake up the user.
          return self.registration.showNotification(title, options);
        }
      })
    );
  } catch (err) {
    console.error('Error parsing push data', err);
  }
});


self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  const urlToOpen = event.notification.data.url;

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there is already a window/tab open with the target URL
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if (client.url.includes(urlToOpen) && 'focus' in client) {
          return client.focus();
        }
      }
      // If not, open a new window
      if (clients.openWindow) {
        return clients.openWindow(urlToOpen);
      }
    })
  );
});
